### ISSUE TITLE
Readme erweitern

### ISSUE THREAD

**Issue by zonky2** [doublespark/contao-form-database-bundle#1]
um das, was die Erweiterung mehr/anders macht als das Standardverhalten von Contao...

**Comment by jamesdevine** [comment]
Contao's "Store form data" function requires you to create a database table with columns that match the form fields. This extension will **automatically save all form submissions** and make them available to view in the backend in one place without having to create a dedicated table.

**Comment by zonky2** [comment]
...sounds like the Leads extension from Terminal 42
